name: unitest-test
on: [push]
jobs:
  unitest-for-shopping_basket:
    runs-on: ubuntu-latest
    steps:
      - name: install dependices
        run: pip install pytest
             pip install coverage
             pip install pytest-cover
      - uses: actions/checkout@v2
      - name: Run unitest
        run: python -m pytest --cov=test_shopping_basket
  
